[database]
database_host = localhost
database_name = airflow_reddit
database_port = 5432
database_username = postgres
database_password = postgres

[file_paths]
input_path = /opt/airflow/data/input
output_path = /opt/airflow/data/output

[api_keys]
reddit_secret_key = sT1jmMvvrPOP--sq67il78fvDEzhiw
reddit_client_id = JP6vdxVLGmqS5wRLNzcr3g

[aws]
aws_access_key_id = AKIAZQ3DUGTIRYGN4D6N
aws_secret_access_key = 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
aws_session_token = FwoGZXIvYXdzEMP//////////wEaDKa9qGWHl+dgTvJYOCJqo2Ptle0Kk2yVUCyH8xe7N9+hPFMU8VTkrfMKvUONHfXPWVREaMOg2HML1eB2Pccc7L+Iw1SQ2MdoRoVw93paaMiWucWnDvrVpg0B+zon+o/+4qGYNhpXpUy4lXLft/tNG4wIZO16QgFPoijl5+K9BjIop8ACEXEylR5RVdtZRSeLfs6i8rgi7JpVHPQG+v6jOKq0keduYuUmpA==
aws_region = us-east-1
aws_bucket_name = scholar-reddit-dataengineering

[etl_settings]
batch_size = 100
error_handling = abort
log_level = info